name: Update Daily.dev DevCard

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          # Use a timestamp to create a unique query string
          TIMESTAMP=$(date +%s)
          
          # Replace the old query string with a new one in README.md
          sed -i "s/\(https:\/\/api\.daily\.dev\/devcards\/.*?type=wide&r=k3i\).*/\1&v=$TIMESTAMP)/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Automated DevCard image refresh"
          git push
